module.exports = async (page) => {
  page.setDefaultTimeout(15000);
  page.setDefaultNavigationTimeout(30000);
  const origin = await page.evaluate(() => window.location.origin);
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => localStorage.clear());
  await page.goto(origin, { waitUntil: 'domcontentloaded' });
  await page.getByRole('heading', { name: 'Your taste. Your tracklist.' }).waitFor();
  await page.getByRole('button', { name: 'Leaderboard', exact: true }).click();
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Leaderboard');
  await page.getByRole('button', { name: 'Setup', exact: true }).click();
  await page.getByRole('heading', { name: 'Tune the room before you draft' }).waitFor();
  await page.getByRole('button', { name: 'Library', exact: true }).click();
  await page.getByPlaceholder('Search title, artist, album, or mood').fill('Dark Fantasy');
  await page.getByRole('heading', { name: 'Dark Fantasy', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await page.getByRole('heading', { name: 'Your A&R Card' }).waitFor();
  await page.getByRole('button', { name: 'Draft Board', exact: true }).click();
  await page.getByRole('button', { name: 'Draft Mode', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.waitFor();
  await page.waitForFunction(() => document.querySelector('[role="dialog"] button') === document.activeElement);
  await dialog.getByRole('button').last().focus();
  await page.keyboard.press('Tab');
  if (!await dialog.getByRole('button').first().evaluate((el) => el === document.activeElement)) throw new Error('Modal focus did not wrap');
  await page.keyboard.press('Escape');
  if (await dialog.count()) throw new Error('Escape did not close modal');
  await page.setViewportSize({ width: 390, height: 844 });
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Home overflows mobile viewport');
  await page.getByRole('button', { name: '1v1 Challenge', exact: true }).click();
  await page.getByRole('dialog').waitFor();
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Friends dialog overflows mobile viewport');
  await page.keyboard.press('Escape');
  await page.goto(`${origin}/share`, { waitUntil: 'domcontentloaded' });
  await page.getByText('This share link is missing its result data.', { exact: false }).waitFor();
  const health = await page.request.get(`${origin}/api/health`);
  if (!health.ok() || (await health.json()).status !== 'ok') throw new Error('Health endpoint failed');
  if (errors.length) throw new Error(errors.join('\n'));
};
