/**
 * Script to expand SONG_LIBRARY in src/data/songs.ts with iconic tracks
 * to eliminate all 37 slot-era gaps.
 *
 * Runs iTunes Search API for each track to resolve:
 * - appleMusicId
 * - appleMusicPreviewUrl (30s official AAC .m4a)
 * - artwork (600x600 high-res)
 * - appleMusicUrl
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SONGS_PATH = resolve(ROOT, 'src/data/songs.ts');
const ITUNES_SEARCH = 'https://itunes.apple.com/search';

interface NewSongDefinition {
  title: string;
  artist: string;
  featuredArtists: string[];
  rawArtistString: string;
  album: string;
  year: number;
  genre: string;
  typeTag: string;
  bpm: number;
  energy: number;
  slots: string[];
  gradient: string;
  audioSynthFreq: number;
  impact: number;
  recognition: number;
  acclaim: number;
  archetypes: string[];
  slotAffinity: Record<string, number>;
  isActualAlbumOpener?: boolean;
  isActualAlbumCloser?: boolean;
  originalAlbumTrackNumber?: number;
}

const NEW_TRACKS: NewSongDefinition[] = [
  // --- MID-ALBUM INTERLUDES ---
  {
    title: 'Wake Up Mr. West',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: 'Late Registration',
    year: 2005,
    genre: 'Hip-Hop',
    typeTag: 'Skit Interlude',
    bpm: 85,
    energy: 55,
    slots: ['mid-interlude'],
    gradient: 'from-amber-950 to-stone-900',
    audioSynthFreq: 330,
    impact: 84,
    recognition: 86,
    acclaim: 88,
    archetypes: ['storytelling', 'introspective'],
    slotAffinity: { 'mid-interlude': 98 },
  },
  {
    title: 'Interlude',
    artist: 'Jay-Z',
    featuredArtists: [],
    rawArtistString: 'Jay-Z',
    album: 'The Black Album',
    year: 2003,
    genre: 'Hip-Hop',
    typeTag: 'Soulful Interlude',
    bpm: 90,
    energy: 60,
    slots: ['mid-interlude'],
    gradient: 'from-stone-950 to-neutral-900',
    audioSynthFreq: 349,
    impact: 82,
    recognition: 80,
    acclaim: 85,
    archetypes: ['lyrical', 'introspective'],
    slotAffinity: { 'mid-interlude': 96 },
  },
  {
    title: 'For Free? (Interlude)',
    artist: 'Kendrick Lamar',
    featuredArtists: [],
    rawArtistString: 'Kendrick Lamar',
    album: 'To Pimp a Butterfly',
    year: 2015,
    genre: 'Jazz Rap',
    typeTag: 'Bebop Poetry Interlude',
    bpm: 118,
    energy: 72,
    slots: ['mid-interlude', 'experimental-flex'],
    gradient: 'from-zinc-950 to-emerald-950',
    audioSynthFreq: 392,
    impact: 88,
    recognition: 85,
    acclaim: 96,
    archetypes: ['experimental', 'lyrical'],
    slotAffinity: { 'mid-interlude': 99, 'experimental-flex': 92 },
  },
  {
    title: 'Fertilizer',
    artist: 'Frank Ocean',
    featuredArtists: [],
    rawArtistString: 'Frank Ocean',
    album: 'channel ORANGE',
    year: 2012,
    genre: 'R&B',
    typeTag: 'Radio Jingle Interlude',
    bpm: 80,
    energy: 48,
    slots: ['mid-interlude'],
    gradient: 'from-orange-950 to-amber-950',
    audioSynthFreq: 440,
    impact: 80,
    recognition: 82,
    acclaim: 90,
    archetypes: ['introspective', 'rnb'],
    slotAffinity: { 'mid-interlude': 97 },
  },
  {
    title: 'Skepta Interlude',
    artist: 'Drake',
    featuredArtists: ['Skepta'],
    rawArtistString: 'Drake feat. Skepta',
    album: 'More Life',
    year: 2017,
    genre: 'Grime',
    typeTag: 'Grime Energy Interlude',
    bpm: 140,
    energy: 82,
    slots: ['mid-interlude', 'gritty-anthem'],
    gradient: 'from-slate-950 to-stone-900',
    audioSynthFreq: 330,
    impact: 85,
    recognition: 88,
    acclaim: 86,
    archetypes: ['street-anthem', 'high-energy'],
    slotAffinity: { 'mid-interlude': 95, 'gritty-anthem': 88 },
  },
  {
    title: 'EXACTLY WHAT YOU RUN FROM YOU END UP CHASING',
    artist: 'Tyler, The Creator',
    featuredArtists: ['Jerrod Carmichael'],
    rawArtistString: 'Tyler, The Creator',
    album: 'IGOR',
    year: 2019,
    genre: 'Neo-Soul',
    typeTag: 'Spoken Interlude',
    bpm: 75,
    energy: 45,
    slots: ['mid-interlude'],
    gradient: 'from-pink-950 to-rose-950',
    audioSynthFreq: 261,
    impact: 86,
    recognition: 88,
    acclaim: 94,
    archetypes: ['cinematic', 'introspective'],
    slotAffinity: { 'mid-interlude': 98 },
  },
  {
    title: "Yebba's Heartbreak",
    artist: 'Drake',
    featuredArtists: ['Yebba'],
    rawArtistString: 'Drake & Yebba',
    album: 'Certified Lover Boy',
    year: 2021,
    genre: 'Soul / R&B',
    typeTag: 'Acoustic Piano Interlude',
    bpm: 72,
    energy: 40,
    slots: ['mid-interlude', 'acoustic-unplugged'],
    gradient: 'from-rose-950 to-purple-950',
    audioSynthFreq: 293,
    impact: 88,
    recognition: 90,
    acclaim: 92,
    archetypes: ['introspective', 'rnb'],
    slotAffinity: { 'mid-interlude': 99, 'acoustic-unplugged': 94 },
  },
  {
    title: 'BLESSED',
    artist: 'Tyler, The Creator',
    featuredArtists: [],
    rawArtistString: 'Tyler, The Creator',
    album: 'CALL ME IF YOU GET LOST',
    year: 2021,
    genre: 'Hip-Hop',
    typeTag: 'Gratitude Interlude',
    bpm: 82,
    energy: 50,
    slots: ['mid-interlude'],
    gradient: 'from-teal-950 to-cyan-950',
    audioSynthFreq: 330,
    impact: 82,
    recognition: 84,
    acclaim: 90,
    archetypes: ['introspective', 'storytelling'],
    slotAffinity: { 'mid-interlude': 96 },
  },
  {
    title: 'Smoking on my Ex Pack',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'SOS',
    year: 2022,
    genre: 'Boom Bap',
    typeTag: 'Bars Interlude',
    bpm: 88,
    energy: 68,
    slots: ['mid-interlude', 'statement-banger'],
    gradient: 'from-blue-950 to-indigo-950',
    audioSynthFreq: 370,
    impact: 90,
    recognition: 92,
    acclaim: 92,
    archetypes: ['lyrical', 'value-pick'],
    slotAffinity: { 'mid-interlude': 98, 'statement-banger': 85 },
  },

  // --- EXPERIMENTAL FLEX ---
  {
    title: 'B.O.B. (Bombs Over Baghdad)',
    artist: 'OutKast',
    featuredArtists: [],
    rawArtistString: 'OutKast',
    album: 'Stankonia',
    year: 2000,
    genre: 'Drum and Bass Rap',
    typeTag: 'Frenetic Tempo Flex',
    bpm: 155,
    energy: 98,
    slots: ['experimental-flex', 'statement-banger', 'apex-climax'],
    gradient: 'from-red-950 to-purple-950',
    audioSynthFreq: 523,
    impact: 98,
    recognition: 96,
    acclaim: 100,
    archetypes: ['experimental', 'high-energy', 'climax'],
    slotAffinity: { 'experimental-flex': 99, 'statement-banger': 92, 'apex-climax': 95 },
  },
  {
    title: 'Grindin',
    artist: 'Clipse',
    featuredArtists: [],
    rawArtistString: 'Clipse',
    album: 'Lord Willin',
    year: 2002,
    genre: 'Hip-Hop',
    typeTag: 'Minimalist Percussion Flex',
    bpm: 97,
    energy: 88,
    slots: ['experimental-flex', 'gritty-anthem'],
    gradient: 'from-slate-950 to-gray-900',
    audioSynthFreq: 440,
    impact: 94,
    recognition: 95,
    acclaim: 98,
    archetypes: ['experimental', 'street-anthem'],
    slotAffinity: { 'experimental-flex': 98, 'gritty-anthem': 94 },
  },
  {
    title: 'Say You Will',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: '808s & Heartbreak',
    year: 2008,
    genre: 'Electropop / Rap',
    typeTag: 'Heartbeat Synth Experiment',
    bpm: 130,
    energy: 65,
    slots: ['experimental-flex', 'cinematic-intro'],
    gradient: 'from-gray-950 to-red-950',
    audioSynthFreq: 261,
    impact: 92,
    recognition: 90,
    acclaim: 95,
    archetypes: ['experimental', 'cinematic', 'iconic-opener'],
    slotAffinity: { 'experimental-flex': 97, 'cinematic-intro': 90 },
    isActualAlbumOpener: true,
  },
  {
    title: 'On Sight',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: 'Yeezus',
    year: 2013,
    genre: 'Industrial Hip-Hop',
    typeTag: 'Abrasive Synth Shock',
    bpm: 116,
    energy: 95,
    slots: ['experimental-flex', 'cinematic-intro'],
    gradient: 'from-red-950 to-zinc-950',
    audioSynthFreq: 494,
    impact: 95,
    recognition: 94,
    acclaim: 96,
    archetypes: ['experimental', 'iconic-opener', 'high-energy'],
    slotAffinity: { 'experimental-flex': 100, 'cinematic-intro': 92 },
    isActualAlbumOpener: true,
  },
  {
    title: 'Blood on the Leaves',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: 'Yeezus',
    year: 2013,
    genre: 'Industrial Trap',
    typeTag: 'Brass Drop Meltdown',
    bpm: 86,
    energy: 94,
    slots: ['experimental-flex', 'apex-climax'],
    gradient: 'from-rose-950 to-red-950',
    audioSynthFreq: 392,
    impact: 96,
    recognition: 95,
    acclaim: 95,
    archetypes: ['experimental', 'climax'],
    slotAffinity: { 'experimental-flex': 99, 'apex-climax': 96 },
  },
  {
    title: 'NEW MAGIC WAND',
    artist: 'Tyler, The Creator',
    featuredArtists: [],
    rawArtistString: 'Tyler, The Creator',
    album: 'IGOR',
    year: 2019,
    genre: 'Noise Rap',
    typeTag: 'Distorted Bass Rage',
    bpm: 140,
    energy: 97,
    slots: ['experimental-flex', 'apex-climax'],
    gradient: 'from-pink-950 to-zinc-950',
    audioSynthFreq: 466,
    impact: 95,
    recognition: 96,
    acclaim: 98,
    archetypes: ['experimental', 'climax', 'high-energy'],
    slotAffinity: { 'experimental-flex': 100, 'apex-climax': 95 },
  },
  {
    title: 'Redbone',
    artist: 'Childish Gambino',
    featuredArtists: [],
    rawArtistString: 'Childish Gambino',
    album: '"Awaken, My Love!"',
    year: 2016,
    genre: 'Psychedelic Soul',
    typeTag: 'Falsetto Funk Revolution',
    bpm: 80,
    energy: 78,
    slots: ['experimental-flex', 'late-night-rnb', 'vibe-shift'],
    gradient: 'from-purple-950 to-amber-950',
    audioSynthFreq: 415,
    impact: 98,
    recognition: 100,
    acclaim: 98,
    archetypes: ['experimental', 'rnb', 'vibe-shift'],
    slotAffinity: { 'experimental-flex': 96, 'late-night-rnb': 94, 'vibe-shift': 92 },
  },
  {
    title: 'United In Grief',
    artist: 'Kendrick Lamar',
    featuredArtists: [],
    rawArtistString: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    year: 2022,
    genre: 'Avant-Garde Rap',
    typeTag: 'Fast Tap Drums & Piano',
    bpm: 115,
    energy: 86,
    slots: ['experimental-flex', 'cinematic-intro'],
    gradient: 'from-neutral-950 to-stone-900',
    audioSynthFreq: 330,
    impact: 92,
    recognition: 90,
    acclaim: 97,
    archetypes: ['experimental', 'cinematic', 'iconic-opener'],
    slotAffinity: { 'experimental-flex': 99, 'cinematic-intro': 95 },
    isActualAlbumOpener: true,
  },
  {
    title: 'MY EYES',
    artist: 'Travis Scott',
    featuredArtists: ['Bon Iver', 'Sampha'],
    rawArtistString: 'Travis Scott',
    album: 'UTOPIA',
    year: 2023,
    genre: 'Psychedelic Rap',
    typeTag: 'Ambient to Sprint Beat Switch',
    bpm: 119,
    energy: 88,
    slots: ['experimental-flex', 'vibe-shift'],
    gradient: 'from-stone-950 to-amber-950',
    audioSynthFreq: 370,
    impact: 96,
    recognition: 98,
    acclaim: 95,
    archetypes: ['experimental', 'vibe-shift'],
    slotAffinity: { 'experimental-flex': 100, 'vibe-shift': 95 },
  },
  {
    title: 'drive ME crazy!',
    artist: 'Lil Yachty',
    featuredArtists: ['Diana Gordon'],
    rawArtistString: 'Lil Yachty feat. Diana Gordon',
    album: "Let's Start Here.",
    year: 2023,
    genre: 'Psychedelic Rock / Funk',
    typeTag: 'Psychedelic Bass Groove',
    bpm: 104,
    energy: 82,
    slots: ['experimental-flex', 'vibe-shift'],
    gradient: 'from-indigo-950 to-purple-950',
    audioSynthFreq: 349,
    impact: 88,
    recognition: 90,
    acclaim: 92,
    archetypes: ['experimental', 'vibe-shift'],
    slotAffinity: { 'experimental-flex': 95, 'vibe-shift': 90 },
  },

  // --- ACOUSTIC / STRIPPED BACK ---
  {
    title: 'Prototype',
    artist: 'OutKast',
    featuredArtists: [],
    rawArtistString: 'OutKast (André 3000)',
    album: 'The Love Below',
    year: 2003,
    genre: 'Funk / Soul',
    typeTag: 'Stripped Bass & Guitar',
    bpm: 78,
    energy: 52,
    slots: ['acoustic-unplugged', 'late-night-rnb'],
    gradient: 'from-pink-950 to-purple-950',
    audioSynthFreq: 261,
    impact: 92,
    recognition: 92,
    acclaim: 97,
    archetypes: ['introspective', 'rnb'],
    slotAffinity: { 'acoustic-unplugged': 98, 'late-night-rnb': 92 },
  },
  {
    title: 'Self Control',
    artist: 'Frank Ocean',
    featuredArtists: [],
    rawArtistString: 'Frank Ocean',
    album: 'Blonde',
    year: 2016,
    genre: 'Indie Soul',
    typeTag: 'Guitar Ballad & Choir',
    bpm: 65,
    energy: 50,
    slots: ['acoustic-unplugged', 'introspective-cut'],
    gradient: 'from-emerald-950 to-teal-950',
    audioSynthFreq: 330,
    impact: 97,
    recognition: 98,
    acclaim: 99,
    archetypes: ['introspective', 'climax'],
    slotAffinity: { 'acoustic-unplugged': 100, 'introspective-cut': 96 },
  },
  {
    title: 'White Ferrari',
    artist: 'Frank Ocean',
    featuredArtists: [],
    rawArtistString: 'Frank Ocean',
    album: 'Blonde',
    year: 2016,
    genre: 'Ambient Folk',
    typeTag: 'Acoustic Strum & Synth Swell',
    bpm: 60,
    energy: 42,
    slots: ['acoustic-unplugged', 'introspective-cut', 'cinematic-outro'],
    gradient: 'from-neutral-950 to-stone-900',
    audioSynthFreq: 293,
    impact: 96,
    recognition: 98,
    acclaim: 99,
    archetypes: ['introspective', 'outro'],
    slotAffinity: { 'acoustic-unplugged': 99, 'introspective-cut': 95, 'cinematic-outro': 90 },
  },
  {
    title: '20 Something',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'Ctrl',
    year: 2017,
    genre: 'Acoustic R&B',
    typeTag: 'Gentle Acoustic Closer',
    bpm: 68,
    energy: 38,
    slots: ['acoustic-unplugged', 'cinematic-outro'],
    gradient: 'from-amber-950 to-stone-950',
    audioSynthFreq: 246,
    impact: 94,
    recognition: 95,
    acclaim: 98,
    archetypes: ['introspective', 'outro'],
    slotAffinity: { 'acoustic-unplugged': 100, 'cinematic-outro': 96 },
    isActualAlbumCloser: true,
  },
  {
    title: 'Best Part',
    artist: 'Daniel Caesar',
    featuredArtists: ['H.E.R.'],
    rawArtistString: 'Daniel Caesar feat. H.E.R.',
    album: 'Freudian',
    year: 2017,
    genre: 'Acoustic Soul',
    typeTag: 'Intimate Dual Vocal',
    bpm: 75,
    energy: 45,
    slots: ['acoustic-unplugged', 'late-night-rnb'],
    gradient: 'from-yellow-950 to-amber-950',
    audioSynthFreq: 261,
    impact: 95,
    recognition: 98,
    acclaim: 95,
    archetypes: ['rnb', 'introspective'],
    slotAffinity: { 'acoustic-unplugged': 98, 'late-night-rnb': 95 },
  },
  {
    title: 'Special',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'SOS',
    year: 2022,
    genre: 'Acoustic Ballad',
    typeTag: 'Raw Vulnerable Acoustic',
    bpm: 70,
    energy: 42,
    slots: ['acoustic-unplugged', 'introspective-cut'],
    gradient: 'from-blue-950 to-slate-950',
    audioSynthFreq: 277,
    impact: 90,
    recognition: 92,
    acclaim: 94,
    archetypes: ['introspective'],
    slotAffinity: { 'acoustic-unplugged': 99, 'introspective-cut': 92 },
  },
  {
    title: 'Nobody Gets Me',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'SOS',
    year: 2022,
    genre: 'Acoustic Rock / R&B',
    typeTag: 'Strummed Power Ballad',
    bpm: 99,
    energy: 58,
    slots: ['acoustic-unplugged', 'introspective-cut'],
    gradient: 'from-indigo-950 to-slate-900',
    audioSynthFreq: 330,
    impact: 95,
    recognition: 97,
    acclaim: 93,
    archetypes: ['introspective', 'rnb'],
    slotAffinity: { 'acoustic-unplugged': 97, 'introspective-cut': 94 },
  },
  {
    title: 'Mercury',
    artist: 'Steve Lacy',
    featuredArtists: [],
    rawArtistString: 'Steve Lacy',
    album: 'Gemini Rights',
    year: 2022,
    genre: 'Bossa Nova / R&B',
    typeTag: 'Acoustic Bossa Chords',
    bpm: 108,
    energy: 60,
    slots: ['acoustic-unplugged', 'vibe-shift'],
    gradient: 'from-amber-950 to-rose-950',
    audioSynthFreq: 349,
    impact: 88,
    recognition: 90,
    acclaim: 92,
    archetypes: ['vibe-shift', 'experimental'],
    slotAffinity: { 'acoustic-unplugged': 95, 'vibe-shift': 90 },
  },

  // --- MELODIC TRAP ---
  {
    title: 'Heartless',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: '808s & Heartbreak',
    year: 2008,
    genre: 'Melodic Rap',
    typeTag: 'Auto-tune Melodic Blueprint',
    bpm: 88,
    energy: 82,
    slots: ['melodic-trap', 'statement-banger'],
    gradient: 'from-slate-950 to-red-950',
    audioSynthFreq: 440,
    impact: 98,
    recognition: 99,
    acclaim: 96,
    archetypes: ['high-energy', 'lyrical'],
    slotAffinity: { 'melodic-trap': 100, 'statement-banger': 90 },
  },
  {
    title: "Day 'n' Nite",
    artist: 'Kid Cudi',
    featuredArtists: [],
    rawArtistString: 'Kid Cudi',
    album: 'Man on the Moon: The End of Day',
    year: 2009,
    genre: 'Alternative Rap',
    typeTag: 'Hypnotic Synth Hook',
    bpm: 138,
    energy: 78,
    slots: ['melodic-trap', 'vibe-shift'],
    gradient: 'from-indigo-950 to-purple-950',
    audioSynthFreq: 392,
    impact: 97,
    recognition: 99,
    acclaim: 95,
    archetypes: ['vibe-shift', 'iconic-opener'],
    slotAffinity: { 'melodic-trap': 98, 'vibe-shift': 92 },
  },
  {
    title: 'XO Tour Llif3',
    artist: 'Lil Uzi Vert',
    featuredArtists: [],
    rawArtistString: 'Lil Uzi Vert',
    album: 'Luv Is Rage 2',
    year: 2017,
    genre: 'Emo Trap',
    typeTag: 'Generation-Defining Hook',
    bpm: 155,
    energy: 88,
    slots: ['melodic-trap', 'apex-climax'],
    gradient: 'from-purple-950 to-pink-950',
    audioSynthFreq: 523,
    impact: 99,
    recognition: 100,
    acclaim: 95,
    archetypes: ['high-energy', 'climax'],
    slotAffinity: { 'melodic-trap': 100, 'apex-climax': 94 },
  },
  {
    title: 'Butterfly Effect',
    artist: 'Travis Scott',
    featuredArtists: [],
    rawArtistString: 'Travis Scott',
    album: 'ASTROWORLD',
    year: 2018,
    genre: 'Psychedelic Trap',
    typeTag: 'Glistening Synth Melodies',
    bpm: 141,
    energy: 85,
    slots: ['melodic-trap', 'vibe-shift'],
    gradient: 'from-amber-950 to-purple-950',
    audioSynthFreq: 440,
    impact: 95,
    recognition: 98,
    acclaim: 90,
    archetypes: ['high-energy', 'vibe-shift'],
    slotAffinity: { 'melodic-trap': 98, 'vibe-shift': 92 },
  },
  {
    title: 'Codeine Crazy',
    artist: 'Future',
    featuredArtists: [],
    rawArtistString: 'Future',
    album: 'Monster',
    year: 2014,
    genre: 'Trap',
    typeTag: 'Melodic Trap Masterpiece',
    bpm: 128,
    energy: 80,
    slots: ['melodic-trap', 'cinematic-outro'],
    gradient: 'from-purple-950 to-slate-950',
    audioSynthFreq: 330,
    impact: 96,
    recognition: 95,
    acclaim: 99,
    archetypes: ['climax', 'outro'],
    slotAffinity: { 'melodic-trap': 99, 'cinematic-outro': 94 },
    isActualAlbumCloser: true,
  },
  {
    title: 'Sky',
    artist: 'Playboi Carti',
    featuredArtists: [],
    rawArtistString: 'Playboi Carti',
    album: 'Whole Lotta Red',
    year: 2020,
    genre: 'Rage / Trap',
    typeTag: 'Hyperpop 808 Anthem',
    bpm: 140,
    energy: 92,
    slots: ['melodic-trap', 'club-bounce', 'statement-banger'],
    gradient: 'from-green-950 to-red-950',
    audioSynthFreq: 494,
    impact: 96,
    recognition: 98,
    acclaim: 92,
    archetypes: ['club', 'high-energy'],
    slotAffinity: { 'melodic-trap': 99, 'club-bounce': 95, 'statement-banger': 90 },
  },
  {
    title: 'Superhero (Heroes & Villains)',
    artist: 'Metro Boomin',
    featuredArtists: ['Future', 'Chris Brown'],
    rawArtistString: 'Metro Boomin, Future & Chris Brown',
    album: 'HEROES & VILLAINS',
    year: 2022,
    genre: 'Trap',
    typeTag: 'Horn Fanfare Trap Peak',
    bpm: 117,
    energy: 94,
    slots: ['melodic-trap', 'statement-banger', 'apex-climax'],
    gradient: 'from-red-950 to-stone-950',
    audioSynthFreq: 466,
    impact: 98,
    recognition: 99,
    acclaim: 94,
    archetypes: ['high-energy', 'climax'],
    slotAffinity: { 'melodic-trap': 98, 'statement-banger': 95, 'apex-climax': 95 },
  },

  // --- STORYTELLER CUT ---
  {
    title: 'Stan',
    artist: 'Eminem',
    featuredArtists: ['Dido'],
    rawArtistString: 'Eminem feat. Dido',
    album: 'The Marshall Mathers LP',
    year: 2000,
    genre: 'Hip-Hop',
    typeTag: 'Letter Narrative Masterpiece',
    bpm: 80,
    energy: 70,
    slots: ['storyteller-cut', 'introspective-cut'],
    gradient: 'from-slate-950 to-zinc-900',
    audioSynthFreq: 330,
    impact: 100,
    recognition: 100,
    acclaim: 100,
    archetypes: ['storytelling', 'lyrical'],
    slotAffinity: { 'storyteller-cut': 100, 'introspective-cut': 90 },
  },
  {
    title: 'Wet Dreamz',
    artist: 'J. Cole',
    featuredArtists: [],
    rawArtistString: 'J. Cole',
    album: '2014 Forest Hills Drive',
    year: 2014,
    genre: 'Hip-Hop',
    typeTag: 'Coming-of-Age Story',
    bpm: 90,
    energy: 75,
    slots: ['storyteller-cut'],
    gradient: 'from-blue-950 to-stone-900',
    audioSynthFreq: 370,
    impact: 96,
    recognition: 98,
    acclaim: 92,
    archetypes: ['storytelling', 'lyrical'],
    slotAffinity: { 'storyteller-cut': 99 },
  },
  {
    title: 'Father Time',
    artist: 'Kendrick Lamar',
    featuredArtists: ['Sampha'],
    rawArtistString: 'Kendrick Lamar feat. Sampha',
    album: 'Mr. Morale & the Big Steppers',
    year: 2022,
    genre: 'Hip-Hop',
    typeTag: 'Daddy Issues Narrative',
    bpm: 82,
    energy: 78,
    slots: ['storyteller-cut', 'introspective-cut'],
    gradient: 'from-stone-950 to-neutral-900',
    audioSynthFreq: 392,
    impact: 94,
    recognition: 92,
    acclaim: 98,
    archetypes: ['storytelling', 'introspective', 'lyrical'],
    slotAffinity: { 'storyteller-cut': 99, 'introspective-cut': 95 },
  },
  {
    title: 'the.climb.back',
    artist: 'J. Cole',
    featuredArtists: [],
    rawArtistString: 'J. Cole',
    album: 'The Off-Season',
    year: 2021,
    genre: 'Hip-Hop',
    typeTag: 'Reflective Grit Narrative',
    bpm: 83,
    energy: 82,
    slots: ['storyteller-cut', 'gritty-anthem'],
    gradient: 'from-amber-950 to-slate-950',
    audioSynthFreq: 349,
    impact: 90,
    recognition: 91,
    acclaim: 94,
    archetypes: ['storytelling', 'lyrical'],
    slotAffinity: { 'storyteller-cut': 96, 'gritty-anthem': 90 },
  },

  // --- CINEMATIC OUTRO ---
  {
    title: 'Last Call',
    artist: 'Kanye West',
    featuredArtists: [],
    rawArtistString: 'Kanye West',
    album: 'The College Dropout',
    year: 2004,
    genre: 'Hip-Hop',
    typeTag: '12-Minute Origin Monologue',
    bpm: 84,
    energy: 74,
    slots: ['cinematic-outro'],
    gradient: 'from-amber-950 to-stone-900',
    audioSynthFreq: 330,
    impact: 94,
    recognition: 92,
    acclaim: 97,
    archetypes: ['outro', 'storytelling'],
    slotAffinity: { 'cinematic-outro': 100 },
    isActualAlbumCloser: true,
  },
  {
    title: 'ARE WE STILL FRIENDS?',
    artist: 'Tyler, The Creator',
    featuredArtists: [],
    rawArtistString: 'Tyler, The Creator',
    album: 'IGOR',
    year: 2019,
    genre: 'Soul / Funk',
    typeTag: 'Heart-Wrenching Screamed Finale',
    bpm: 72,
    energy: 80,
    slots: ['cinematic-outro', 'apex-climax'],
    gradient: 'from-pink-950 to-rose-950',
    audioSynthFreq: 370,
    impact: 96,
    recognition: 98,
    acclaim: 99,
    archetypes: ['outro', 'climax'],
    slotAffinity: { 'cinematic-outro': 100, 'apex-climax': 90 },
    isActualAlbumCloser: true,
  },
  {
    title: 'So It Goes',
    artist: 'Mac Miller',
    featuredArtists: [],
    rawArtistString: 'Mac Miller',
    album: 'Swimming',
    year: 2018,
    genre: 'Alternative Rap',
    typeTag: 'Orchestral Ascending Finale',
    bpm: 70,
    energy: 60,
    slots: ['cinematic-outro'],
    gradient: 'from-blue-950 to-slate-900',
    audioSynthFreq: 261,
    impact: 95,
    recognition: 94,
    acclaim: 99,
    archetypes: ['outro', 'cinematic'],
    slotAffinity: { 'cinematic-outro': 100 },
    isActualAlbumCloser: true,
  },
  {
    title: 'Mirror',
    artist: 'Kendrick Lamar',
    featuredArtists: [],
    rawArtistString: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    year: 2022,
    genre: 'Hip-Hop',
    typeTag: 'Redemption & Grace Outro',
    bpm: 75,
    energy: 68,
    slots: ['cinematic-outro', 'introspective-cut'],
    gradient: 'from-stone-950 to-amber-950',
    audioSynthFreq: 293,
    impact: 90,
    recognition: 90,
    acclaim: 95,
    archetypes: ['outro', 'introspective'],
    slotAffinity: { 'cinematic-outro': 99, 'introspective-cut': 92 },
    isActualAlbumCloser: true,
  },
  {
    title: 'Less Than Zero',
    artist: 'The Weeknd',
    featuredArtists: [],
    rawArtistString: 'The Weeknd',
    album: 'Dawn FM',
    year: 2022,
    genre: 'Synth-Pop',
    typeTag: 'Bittersweet Euphoria Closer',
    bpm: 130,
    energy: 88,
    slots: ['cinematic-outro', 'vibe-shift'],
    gradient: 'from-blue-950 to-indigo-950',
    audioSynthFreq: 440,
    impact: 95,
    recognition: 97,
    acclaim: 96,
    archetypes: ['outro', 'vibe-shift'],
    slotAffinity: { 'cinematic-outro': 98, 'vibe-shift': 94 },
    isActualAlbumCloser: true,
  },

  // --- LATE-NIGHT R&B ---
  {
    title: 'Ex-Factor',
    artist: 'Ms. Lauryn Hill',
    featuredArtists: [],
    rawArtistString: 'Ms. Lauryn Hill',
    album: 'The Miseducation of Lauryn Hill',
    year: 1998,
    genre: 'Neo-Soul / R&B',
    typeTag: 'Eternal Heartbreak Anthem',
    bpm: 80,
    energy: 60,
    slots: ['late-night-rnb', 'introspective-cut'],
    gradient: 'from-amber-950 to-yellow-950',
    audioSynthFreq: 330,
    impact: 100,
    recognition: 100,
    acclaim: 100,
    archetypes: ['rnb', 'introspective'],
    slotAffinity: { 'late-night-rnb': 100, 'introspective-cut': 95 },
  },
  {
    title: 'Thinkin Bout You',
    artist: 'Frank Ocean',
    featuredArtists: [],
    rawArtistString: 'Frank Ocean',
    album: 'channel ORANGE',
    year: 2012,
    genre: 'R&B',
    typeTag: 'Iconic Falsetto Opener',
    bpm: 65,
    energy: 55,
    slots: ['late-night-rnb', 'cinematic-intro'],
    gradient: 'from-orange-950 to-amber-950',
    audioSynthFreq: 349,
    impact: 99,
    recognition: 100,
    acclaim: 99,
    archetypes: ['rnb', 'iconic-opener'],
    slotAffinity: { 'late-night-rnb': 100, 'cinematic-intro': 90 },
    isActualAlbumOpener: true,
  },
  {
    title: 'Pink + White',
    artist: 'Frank Ocean',
    featuredArtists: ['Beyoncé'],
    rawArtistString: 'Frank Ocean (feat. Beyoncé backing vocals)',
    album: 'Blonde',
    year: 2016,
    genre: 'Neo-Soul',
    typeTag: 'Sunlight Piano Groove',
    bpm: 80,
    energy: 65,
    slots: ['late-night-rnb', 'vibe-shift'],
    gradient: 'from-pink-950 to-amber-950',
    audioSynthFreq: 392,
    impact: 98,
    recognition: 100,
    acclaim: 100,
    archetypes: ['rnb', 'vibe-shift'],
    slotAffinity: { 'late-night-rnb': 98, 'vibe-shift': 95 },
  },
  {
    title: 'The Weekend',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'Ctrl',
    year: 2017,
    genre: 'R&B',
    typeTag: 'Hypnotic Midnight Confession',
    bpm: 102,
    energy: 55,
    slots: ['late-night-rnb'],
    gradient: 'from-teal-950 to-emerald-950',
    audioSynthFreq: 293,
    impact: 97,
    recognition: 99,
    acclaim: 98,
    archetypes: ['rnb'],
    slotAffinity: { 'late-night-rnb': 100 },
  },
  {
    title: 'Kill Bill',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'SOS',
    year: 2022,
    genre: 'Pop R&B',
    typeTag: 'Global Revenge Sensation',
    bpm: 118,
    energy: 73,
    slots: ['late-night-rnb', 'statement-banger', 'vibe-shift'],
    gradient: 'from-red-950 to-rose-950',
    audioSynthFreq: 370,
    impact: 100,
    recognition: 100,
    acclaim: 96,
    archetypes: ['rnb', 'vibe-shift', 'high-energy'],
    slotAffinity: { 'late-night-rnb': 98, 'statement-banger': 94, 'vibe-shift': 95 },
  },
  {
    title: 'Bad Habit',
    artist: 'Steve Lacy',
    featuredArtists: [],
    rawArtistString: 'Steve Lacy',
    album: 'Gemini Rights',
    year: 2022,
    genre: 'Indie R&B',
    typeTag: 'Infectious Guitar Earworm',
    bpm: 85,
    energy: 72,
    slots: ['late-night-rnb', 'vibe-shift', 'statement-banger'],
    gradient: 'from-amber-950 to-purple-950',
    audioSynthFreq: 415,
    impact: 99,
    recognition: 100,
    acclaim: 96,
    archetypes: ['rnb', 'vibe-shift'],
    slotAffinity: { 'late-night-rnb': 98, 'vibe-shift': 96, 'statement-banger': 90 },
  },
  {
    title: 'CUFF IT',
    artist: 'Beyoncé',
    featuredArtists: [],
    rawArtistString: 'Beyoncé',
    album: 'RENAISSANCE',
    year: 2022,
    genre: 'Disco Funk / R&B',
    typeTag: 'Irresistible Roller Rink Groove',
    bpm: 115,
    energy: 88,
    slots: ['club-bounce', 'vibe-shift', 'late-night-rnb'],
    gradient: 'from-amber-950 to-fuchsia-950',
    audioSynthFreq: 466,
    impact: 98,
    recognition: 100,
    acclaim: 98,
    archetypes: ['club', 'vibe-shift', 'high-energy'],
    slotAffinity: { 'club-bounce': 99, 'vibe-shift': 96, 'late-night-rnb': 90 },
  },

  // --- 2020s CINEMATIC INTROS ---
  {
    title: 'HYAENA',
    artist: 'Travis Scott',
    featuredArtists: [],
    rawArtistString: 'Travis Scott',
    album: 'UTOPIA',
    year: 2023,
    genre: 'Boom Bap / Trap',
    typeTag: 'Tribal Sample Overture',
    bpm: 91,
    energy: 86,
    slots: ['cinematic-intro', 'statement-banger'],
    gradient: 'from-stone-950 to-amber-950',
    audioSynthFreq: 440,
    impact: 94,
    recognition: 95,
    acclaim: 93,
    archetypes: ['iconic-opener', 'high-energy'],
    slotAffinity: { 'cinematic-intro': 98, 'statement-banger': 92 },
    isActualAlbumOpener: true,
  },
  {
    title: 'SIR BAUDELAIRE',
    artist: 'Tyler, The Creator',
    featuredArtists: ['DJ Drama'],
    rawArtistString: 'Tyler, The Creator feat. DJ Drama',
    album: 'CALL ME IF YOU GET LOST',
    year: 2021,
    genre: 'Hip-Hop',
    typeTag: 'Luxury Gangsta Grillz Intro',
    bpm: 80,
    energy: 78,
    slots: ['cinematic-intro'],
    gradient: 'from-teal-950 to-cyan-950',
    audioSynthFreq: 349,
    impact: 92,
    recognition: 93,
    acclaim: 95,
    archetypes: ['iconic-opener', 'cinematic'],
    slotAffinity: { 'cinematic-intro': 98 },
    isActualAlbumOpener: true,
  },
  {
    title: 'Seek & Destroy',
    artist: 'SZA',
    featuredArtists: [],
    rawArtistString: 'SZA',
    album: 'SOS',
    year: 2022,
    genre: 'R&B / Trap',
    typeTag: 'High-Impact Trap Opener',
    bpm: 85,
    energy: 80,
    slots: ['cinematic-intro', 'statement-banger'],
    gradient: 'from-blue-950 to-teal-950',
    audioSynthFreq: 392,
    impact: 93,
    recognition: 95,
    acclaim: 94,
    archetypes: ['iconic-opener', 'high-energy'],
    slotAffinity: { 'cinematic-intro': 95, 'statement-banger': 90 },
  },
];

async function resolveItunes(title: string, artist: string) {
  const query = `${title} ${artist}`.slice(0, 100);
  const url = `${ITUNES_SEARCH}?term=${encodeURIComponent(query)}&entity=song&limit=5&country=US`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const data = (await res.json()) as {
      results: Array<{
        trackId: number;
        previewUrl?: string;
        artworkUrl100?: string;
        trackViewUrl?: string;
      }>;
    };
    const match = data.results?.find((r) => r.previewUrl);
    if (!match) return null;
    return {
      appleMusicId: String(match.trackId),
      appleMusicPreviewUrl: match.previewUrl,
      artwork: match.artworkUrl100 ? match.artworkUrl100.replace('100x100bb.jpg', '600x600bb.jpg') : undefined,
      appleMusicUrl: match.trackViewUrl,
    };
  } catch {
    return null;
  }
}

async function main() {
  console.log(`Resolving ${NEW_TRACKS.length} curated tracks via iTunes Search API...`);
  const resolvedList = [];

  let nextIdNum = 126;
  for (const track of NEW_TRACKS) {
    process.stdout.write(`Fetching ${track.title} by ${track.artist}... `);
    const meta = await resolveItunes(track.title, track.artist);
    const songId = `song-${nextIdNum++}`;

    const completeSong = {
      id: songId,
      ...track,
      ...(meta || {}),
    };

    resolvedList.push(completeSong);
    console.log(meta?.appleMusicPreviewUrl ? '✓ RESOLVED' : '⚠ NO PREVIEW');
    // Polite delay
    await new Promise((r) => setTimeout(r, 120));
  }

  // Read songs.ts
  const content = readFileSync(SONGS_PATH, 'utf-8');

  // Insert before `];\n\n/**\n * Filter songs by era.`
  const insertIndex = content.indexOf('];\n\n/**\n * Filter songs by era.');
  if (insertIndex === -1) {
    console.error('Could not locate end of SONG_LIBRARY array!');
    process.exit(1);
  }

  const generatedCode = resolvedList
    .map((s) => `  ${JSON.stringify(s, null, 2).replace(/\n/g, '\n  ')},`)
    .join('\n');

  const newContent = content.slice(0, insertIndex) + generatedCode + '\n' + content.slice(insertIndex);
  writeFileSync(SONGS_PATH, newContent, 'utf-8');
  console.log(`\nSuccessfully added ${resolvedList.length} new songs to ${SONGS_PATH}!`);
}

main().catch(console.error);
